#!/bin/bash
# Git clone shortcut with pre-commit initialization

if [[ $1 == "-h" || $1 == "--help" ]]; then
    git clone --help
    exit 0
fi

if [[ ! $(command -v pre-commit) ]]; then
    echo "pre-commit could not be found and is required to run this script"
    exit 1
fi

git clone $1 ${@:2} && cd $(basename "$1" .git)
pre-commit install 2> /dev/null
