#!/bin/bash
# Create provided tag on project

TAG_NAME=$1
TAG_MESSAGE=${@:2}

if [[ -z $TAG_NAME ]]; then
  echo "must provide a tag name"
  exit 1
fi

if [[ -z TAG_MESSAGE ]]; then
  echo "must provide a tag message"
  exit 1
fi

gpa
git tag -a "$TAG_NAME" -m "${TAG_MESSAGE[@]}"
git push --tags --force
git fetch --all --tags -–prune