#!/bin/bash
# Create provided tag on project

TAG_NAME=$1
TAG_MESSAGE=$(git branch | grep '*' | cut -d' ' -f2)

if [[ -z $TAG_NAME ]]; then
  echo "must provide a tag name"
  exit 1
fi

gpa
git tag --force -a "$TAG_NAME" -m "${TAG_MESSAGE[@]}"
git push --tags --force
git fetch --all --tags
